name: GuestBook CI/CD Pipeline

on:
  push:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      run: |
        ls -l ~/
        git clone https://github.com/0zeroxzero0/guestbook.git
        tree -L 5 ~/work/guestbook